config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :cocktails do
    resources :doses, only: [:new, :create, :destroy]
  end

end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  validates :name, uniqueness: true, presence:true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ActiveRecord::Base
  validates :description, presence: true
  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates :cocktail_id, :uniqueness => { :scope => :ingredient_id }
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :cocktail
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @ingredients = @cocktail.ingredients
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.create(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end


end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_cocktail, only: [ :new, :create ]


  def new
    @dose = Dose.new
    @ingredients = Ingredient.all
  end

  def create
    @dose = @cocktail.doses.build(dose_params)
    ingredient = Ingredient.find(params[:dose][:ingredient].to_i)
    @dose.ingredient = ingredient
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Cocktail.find(params[:dose])
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description)
  end
  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<h1>Here are the cocktails</h1>

<% @cocktails.each do |cocktail|%>
<h2><%= cocktail.name.capitalize%></h2>
<p style = unlisted><%= link_to "See more", cocktail_path(cocktail) %></p>
<% end%>

app/views/cocktails/new.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/cocktails/show.html.erb
<h1>Here are the details about the cocktail:<%= @cocktail.name.capitalize%> </h1>
<!-- <h1><%=@cocktail.ingredients%> </h1> -->

<h2>Ingredients</h2>

<% @cocktail.ingredients.each do |ingredient|%>
  <li><%= ingredient.name.capitalize%></li>
<% end%>

<h2>Recipe / Dose</h2>

<% @cocktail.doses.each do |dose|%>
  <li><%= dose.description.capitalize+ " "+ dose.ingredient.name%> </li>
  <%= link_to "Suppress this dose", cocktail_dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } %>
<% end%>

<%= link_to "Back to all", cocktails_path %>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.error_notification %>
  <%= f.input :description %>
<!-- Menu déroulant avec les ingrédients -->
  <%= f.input :ingredient, collection: @ingredients %>
  <%= f.submit "Add a dose" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMisterCocktail</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>